'use strict';
const STORAGE='bodyflow.records.v1';
const NS='http://www.w3.org/2000/svg';
const rnd=(i,k)=>Math.abs(((i*73856093)^(k*19349663))%1000)/1000;
const D2R=Math.PI/180,pol=(cx,cy,r,deg)=>[cx+r*Math.cos(deg*D2R),cy+r*Math.sin(deg*D2R)];
let INK,PAPER,MUTED,GRID,SECOND;
const limits={weight:[20,400],kcal:[0,10000],carbs:[0,2000],protein:[0,1000],fat:[0,1000],sodium:[0,100000],strength:[0,1440],cardio:[0,1440]};
const editableLimits={weight:limits.weight,strength:limits.strength,cardio:limits.cardio},nutritionKeys=['kcal','carbs','protein','fat','sodium'];
const recordOptions={meal_amount:['high','normal','low'],pain_areas:['knee','back','ankle','shoulder','none'],pain_intensity:['slight','moderate','severe'],session_status:['completed','stopped','skipped']};
const addDays=(date,n)=>{const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function validDate(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&s>='1900-01-01'&&s<='2100-12-31'&&Number.isFinite(Date.parse(s))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s}
function validateCombination(value){if(value===null||value===undefined)return null;if(!value||typeof value.name!=='string'||value.name.length>40||!Array.isArray(value.items)||!value.items.length||value.items.length>20)throw Error('음식 조합 형식을 확인해 주세요.');const items=value.items.map(entry=>{if(!entry||!FoodCombination.validFood(entry.food)||!Number.isFinite(entry.amount_g)||entry.amount_g<10||entry.amount_g>5000)throw Error('식약처 음식 조합을 확인해 주세요.');return {food:entry.food,amount_g:entry.amount_g}});return {name:value.name,items,totals:FoodCombination.totalsOf(items)}}
function validateRows(rows){if(!Array.isArray(rows)||rows.length>3660)throw Error('기록은 3,660개 이하의 배열이어야 합니다.');const seen=new Set();return rows.map(r=>{if(!r||!validDate(r.date)||seen.has(r.date))throw Error('잘못되거나 중복된 날짜가 있습니다.');seen.add(r.date);const out={date:r.date};for(const [key,[lo,hi]]of Object.entries(editableLimits)){const v=r[key]??null;if(v!==null&&(typeof v!=='number'||!Number.isFinite(v)||v<lo||v>hi))throw Error(key+' 값의 범위를 확인하세요.');if(v!==null&&['strength','cardio'].includes(key)&&!Number.isInteger(v))throw Error(key+' 항목은 정수로 입력하세요.');out[key]=v;}const combination=validateCombination(r.food_combination),meals=r.meals??[];if(!Array.isArray(meals)||meals.length>3||new Set(meals.map(meal=>meal.slot)).size!==meals.length)throw Error('끼니 기록 형식을 확인해 주세요.');out.meals=meals.map(meal=>{if(!meal||!['breakfast','lunch','dinner'].includes(meal.slot)||(meal.amount!=null&&!recordOptions.meal_amount.includes(meal.amount)))throw Error('끼니 선택값을 확인해 주세요.');return {slot:meal.slot,amount:meal.amount??null,food_combination:validateCombination(meal.food_combination)}});out.food_combination=combination??out.meals.map(meal=>meal.food_combination).filter(Boolean).at(-1)??null;const officialCombinations=out.meals.length?out.meals.map(meal=>meal.food_combination).filter(Boolean):combination?[combination]:[];out.nutrition_source=officialCombinations.length?'mfds':null;for(const key of nutritionKeys)out[key]=officialCombinations.length?Math.round(officialCombinations.reduce((sum,combo)=>sum+combo.totals[key],0)*10)/10:null;for(const key of ['meal_amount','pain_intensity','session_status']){const v=r[key]??null;if(v!==null&&!recordOptions[key].includes(v))throw Error(key+' 선택값을 확인하세요.');out[key]=v;}const pain=r.pain_areas??[];if(!Array.isArray(pain)||new Set(pain).size!==pain.length||pain.some(v=>!recordOptions.pain_areas.includes(v))||(pain.includes('none')&&pain.length!==1))throw Error('통증 부위 선택값을 확인하세요.');out.pain_areas=[...pain];if(pain.some(v=>v!=='none')&&!out.pain_intensity)throw Error('통증 강도를 선택해 주세요.');if((!pain.length||pain.includes('none'))&&out.pain_intensity!==null)throw Error('통증 없음 기록에는 강도를 저장하지 않습니다.');const rpe=r.session_rpe??null;if(rpe!==null&&(!Number.isInteger(rpe)||rpe<1||rpe>10))throw Error('세션 RPE는 1~10 정수여야 합니다.');if(out.session_status==='completed'&&rpe===null)throw Error('완료한 세션의 RPE를 기록해 주세요.');if(out.session_status!=='completed'&&rpe!==null)throw Error('완료한 세션에만 RPE를 저장할 수 있습니다.');out.session_rpe=rpe;return out}).sort((a,b)=>a.date.localeCompare(b.date))}
function createDemo(){return Array.from({length:30},(_,i)=>{const d={date:addDays('2026-08-14',i),weight:i%9===4?null:+(65.5-i*.032+(rnd(i+1,6)-.5)*.3).toFixed(1),kcal:null,carbs:null,protein:null,fat:null,sodium:null,food_combination:null,nutrition_source:null,strength:0,cardio:0};if(i>=16&&i<23){d.strength=[10,0,10,0,15,0,0][i-16];d.cardio=[20,0,25,0,25,0,0][i-16];}if(i>=23){d.weight=[64.8,64.7,null,64.6,64.9,64.5,64.4][i-23];d.strength=[15,0,15,0,15,0,0][i-23];d.cardio=[20,0,25,0,25,25,0][i-23];}return d})}
const DEMO=createDemo();let profile=null;let own=[],mode='demo',days=7,tab='today',storageWarning='';
try{const raw=localStorage.getItem(STORAGE);if(raw){const payload=JSON.parse(raw);if(payload.version!==1)throw Error('지원하지 않는 저장 버전');const loadedRows=validateRows(payload.records);const loadedProfile=validateProfile(payload.profile??null);own=loadedRows;profile=loadedProfile}const theme=localStorage.getItem('bodyflow.theme');if(['dark','light'].includes(theme))document.documentElement.dataset.theme=theme}catch(e){storageWarning='저장된 데이터를 읽지 못했습니다. 원본 저장값은 변경하지 않았습니다.'}
const records=()=>mode==='demo'?DEMO:own;
const lastDate=()=>records().at(-1)?.date||today();
function rangeRows(count,end=lastDate()){const map=new Map(records().map(r=>[r.date,r]));return Array.from({length:count},(_,i)=>{const date=addDays(end,i-count+1);return map.get(date)||Object.fromEntries([['date',date],...Object.keys(limits).map(k=>[k,null])])})}
const weekRows=()=>rangeRows(7),weightRows=()=>rangeRows(days),latestRecord=()=>records().at(-1);
function activityPairs(){const recent=rangeRows(7),prior=rangeRows(7,addDays(lastDate(),-7));return [['근력','strength'],['유산소','cardio']].map(([name,k])=>[name,prior.reduce((a,r)=>a+(r[k]||0),0),recent.reduce((a,r)=>a+(r[k]||0),0)])}
const el=(p,t,a)=>{const n=document.createElementNS(NS,t);for(const k in a)n.setAttribute(k,a[k]);p.appendChild(n);return n};
const txt=(p,a,s)=>{const n=el(p,'text',a);n.textContent=s;return n};
function tip(n,s){const t=document.createElementNS(NS,'title');t.textContent=s;n.appendChild(t);n.dataset.tip=s;n.setAttribute('tabindex','0');n.setAttribute('role','button');n.setAttribute('aria-label',s)}
function emptyChart(s){txt(s,{x:200,y:140,'text-anchor':'middle','font-size':18,fill:MUTED},'기록을 기다리고 있어요');txt(s,{x:200,y:169,'text-anchor':'middle','font-size':12,fill:MUTED},'오늘 기록에서 한 항목만 시작해도 괜찮아요')}
// 러닝 차트 데이터. 내 기록 모드에 프로필과 계획이 있으면 이번 주 걷기·달리기 세션(실제 계획값)을,
// 아니면 고정 루틴 예시를 쓴다. 준비·정리 운동은 걷기로 간주하지 않고 따로 표시한다.
const RUNNING_EXAMPLE={source:'example',stages:[['준비',[5,0,0]],['본운동',[12,8,0]],['마무리',[5,0,0]]]};
function runningStages(){
  if(mode!=='own'||!profile||!window.BodyFlowAdaptive)return RUNNING_EXAMPLE;
  const state=BodyFlowAdaptive.state();if(!state.startDate||!state.weeks.length)return RUNNING_EXAMPLE;
  const index=Math.floor((Date.parse(today()+'T12:00:00')-Date.parse(state.startDate+'T12:00:00'))/86400000/7),week=state.weeks[index];
  if(!week)return RUNNING_EXAMPLE;
  const session=week.sessions.find(item=>item.type==='run');
  if(!session)return {source:'plan',stages:null,rest:Boolean(week.isRestWeek)};
  const sum=activity=>Math.round(session.blocks.filter(block=>block.activity===activity).reduce((total,block)=>total+block.minutes,0));
  return {source:'plan',day:session.day,stages:[['준비',[0,0,Math.round(session.warmup_min)]],['본운동',[sum('walk'),sum('run'),0]],['마무리',[0,0,Math.round(session.cooldown_min)]]],repeats:session.blocks.filter(block=>block.activity==='run').length};
}
const RUNNING_DAY={monday:'월요일',tuesday:'화요일',wednesday:'수요일',thursday:'목요일',friday:'금요일',saturday:'토요일',sunday:'일요일'};
function describeRunningCard(){
  const card=document.getElementById('running-chart')?.closest('.chart-card');if(!card)return;const info=runningStages(),h2=card.querySelector('h2'),sub=card.querySelector('.sub'),explanation=card.querySelector('.explanation'),src=card.querySelector('.src');
  if(info.source==='example'){h2.textContent='30분을 내 속도로 나눠요';sub.textContent='준비 5분 → 본운동 20분 → 마무리 5분';explanation.textContent='본운동은 달리기 2분 + 걷기 3분을 4회 반복하는 예시입니다. 몸상태에 따라 조절하세요. 실제 타이머·GPS는 연결되지 않았습니다.';src.textContent='F7 · STACKED RUNGS · 고정 루틴 예시';return;}
  if(!info.stages){h2.textContent=info.rest?'이번 주는 쉬는 주간이에요':'이번 주 계획에 걷기·달리기 세션이 없어요';sub.textContent='내 계획 · 이번 주';explanation.textContent='계획 탭에서 이번 주 세션을 확인할 수 있어요. 실제 타이머·GPS는 연결되지 않았습니다.';src.textContent='F7 · STACKED RUNGS · 내 계획';return;}
  const [warm,main,cool]=info.stages.map(([,segs])=>segs[0]+segs[1]+segs[2]),walk=info.stages[1][1][0],run=info.stages[1][1][1];
  h2.textContent=`${warm+main+cool}분을 내 속도로 나눠요`;sub.textContent=`${RUNNING_DAY[info.day]} 세션 · 준비 ${warm}분 → 본운동 ${main}분 → 마무리 ${cool}분`;
  explanation.textContent=(run?`본운동은 달리기 ${run}분과 걷기 ${walk}분을 ${info.repeats}회로 나눈 내 계획입니다.`:`본운동은 걷기 ${walk}분으로 구성된 내 계획입니다.`)+' 몸상태에 따라 조절하세요. 실제 타이머·GPS는 연결되지 않았습니다.';src.textContent='F7 · STACKED RUNGS · 내 계획 · 이번 주';
}
const charts={'nutrition-chart':drawNutrition,'calories-chart':drawCalories,'recipe-chart':drawRecipe,'weight-chart':drawWeight,'activity-chart':drawActivity,'running-chart':drawRunning,'pace-chart':drawPace};
function colors(){const style=getComputedStyle(document.documentElement);INK=style.getPropertyValue('--accent').trim();PAPER=style.getPropertyValue('--surface').trim();MUTED=style.getPropertyValue('--muted').trim();GRID=style.getPropertyValue('--grid').trim();SECOND=style.getPropertyValue('--secondary').trim()}
function renderChart(id){colors();const s=document.getElementById(id);s.replaceChildren();const noOfficialNutrition=id==='nutrition-chart'&&!latestRecord()?.food_combination||id==='calories-chart'&&weekRows().every(r=>!r.food_combination)||id==='recipe-chart'&&!latestRecord()?.food_combination;if(noOfficialNutrition)emptyChart(s);else charts[id](s);if(id==='running-chart')describeRunningCard();if(typeof decoratePresetChart==='function')decoratePresetChart(id,s);if(typeof updateChartSummary==='function')updateChartSummary(id);s.closest('.chart-card').querySelector('.readout').textContent='수치를 누르거나 데이터 표에서 자세히 확인하세요.';}
function tableFor(id){switch(id){case 'weight-chart':return [['날짜','체중 kg'],...weightRows().map(r=>[r.date,r.weight??'미측정'])];case 'calories-chart':return [['날짜','kcal'],...weekRows().map(r=>[r.date,r.kcal??'미기록'])];case 'nutrition-chart':{const r=latestRecord();return [['영양소','기록 g','예시 목표 g'],['탄수화물',r?.carbs??'미기록',180],['단백질',r?.protein??'미기록',90],['지방',r?.fat??'미기록',60]]}case 'activity-chart':return [['활동','이전 7일 분','최근 7일 분'],...activityPairs()];case 'recipe-chart':{const r=latestRecord();if(!r?.food_combination)return [['영양소','에너지 kcal','비중']];const values=[['탄수화물',(r.carbs||0)*4],['단백질',(r.protein||0)*4],['지방',(r.fat||0)*9]],total=values.reduce((sum,row)=>sum+row[1],0);return [['영양소','에너지 kcal','반올림 비중'],...values.map(row=>[row[0],Math.round(row[1]),total?Math.round(row[1]/total*100)+'%':'0%'])]}case 'pace-chart':return [['거리','시간'],['1 km','9분 40초'],['2 km','9분 20초'],['3 km','9분 10초'],['마지막 0.2 km','1분 50초']];case 'running-chart':{const info=runningStages();return [['단계','걷기 분','달리기 분','준비·정리 분'],...(info.stages||[]).map(([name,segs])=>[name,segs[0],segs[1],segs[2]])]}}}
function renderTables(){document.querySelectorAll('[data-table]').forEach(host=>{host.replaceChildren();const table=document.createElement('table');tableFor(host.dataset.table).forEach((row,i)=>{const tr=table.insertRow();for(const value of row){const c=document.createElement(i?'td':'th');c.textContent=value;if(!i)c.scope='col';tr.appendChild(c)}});host.appendChild(table)})}
function render(){document.getElementById('theme').textContent=document.documentElement.dataset.theme==='dark'?'라이트 테마':'다크 테마';document.getElementById('mode-label').textContent=mode==='demo'?'예시 데이터':'내 기록 · 이 기기';document.getElementById('period-label').textContent=lastDate()+' 기준';document.getElementById('demo-mode').setAttribute('aria-pressed',mode==='demo');document.getElementById('own-mode').setAttribute('aria-pressed',mode==='own');document.getElementById('storage-notice').textContent=storageWarning;document.getElementById('calorie-total').textContent=latestRecord()?.kcal?.toLocaleString()??'—';document.getElementById('calorie-source').hidden=!latestRecord()?.food_combination;const vals=weekRows().filter(r=>r.food_combination&&r.kcal!==null);document.getElementById('record-days').textContent=vals.length+' / 7';document.getElementById('calories-title').textContent=vals.length?'기록일 평균 '+Math.round(vals.reduce((a,r)=>a+r.kcal,0)/vals.length).toLocaleString()+' kcal':'아직 섭취 기록이 없어요';const weights=weightRows().filter(r=>r.weight!==null);document.getElementById('weight-title').textContent=weights.length?weights.at(-1).weight.toFixed(1)+' kg · 마지막 측정':'나의 체중 흐름';document.getElementById('weight-sub').textContent=days+'일 · '+weights.length+'회 측정'+(weights.length>1?' · 첫 기록 대비 '+(weights.at(-1).weight-weights[0].weight).toFixed(1)+' kg':'');for(const id of Object.keys(charts))renderChart(id);renderTables();if(typeof renderInsights==='function')renderInsights();if(typeof renderQuickRecords==='function')renderQuickRecords();if(typeof renderAdaptivePlan==='function')renderAdaptivePlan();document.querySelectorAll('[data-days]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.days===days));}
function setTab(next){if(!['today','plan','progress','more'].includes(next))next='today';tab=next;document.querySelectorAll('.tab-panel').forEach(s=>s.hidden=s.id!==next);document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===next);b.setAttribute('aria-current',b.dataset.tab===next?'page':'false')});const titles={today:['TODAY / 01','오늘 할 일에<br>집중해요.','계획을 확인하고 내 몸 상태에 맞춰 시작하세요.'],plan:['PLAN / 02','4주의 흐름을<br>한눈에 봐요.','진행도와 계획이 바뀐 이유를 함께 확인하세요.'],progress:['GROW / 03','나의 변화를<br>천천히 봐요.','식단 · 몸 · 운동으로 나눠 요약부터 살펴보세요.'],more:['MORE / 04','설정과 자료를<br>모아 뒀어요.','계획 설정, 기록 백업, 참고 콘텐츠를 확인하세요.']};document.getElementById('section-tag').textContent=titles[next][0];document.getElementById('page-title').innerHTML=titles[next][1];document.getElementById('page-sub').textContent=titles[next][2];location.hash=next;for(const svg of document.querySelectorAll('#'+next+' svg'))renderChart(svg.id)}
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify({version:1,records:own,profile}));storageWarning='이 기기에 저장했습니다. 서버로 전송하지 않았습니다.';return true}catch(e){storageWarning='브라우저에 저장하지 못했습니다. 현재 화면에만 유지되므로 JSON으로 내보내 주세요.';return false}}
const form=document.getElementById('log-form'),dialog=document.getElementById('log-dialog');
let undoState=null;
function offerUndo(previous,date,message){undoState={previous,date};document.getElementById('undo-message').textContent=message;document.getElementById('undo-banner').hidden=false}
document.getElementById('undo-record').onclick=()=>{if(!undoState)return;const before=own;own=validateRows(BodyFlowRecord.restoreRecord(own,undoState.date,undoState.previous));if(!persist()){own=before;document.getElementById('undo-message').textContent='되돌리기를 완료하지 못했습니다. 저장 공간을 확인해 주세요.';return}undoState=null;document.getElementById('undo-banner').hidden=true;render()};
const weightRange=document.getElementById('weight-range'),weightValue=document.getElementById('weight-value'),weightSource=document.getElementById('weight-source');
function selectOne(selector,value){document.querySelectorAll(selector).forEach(button=>button.setAttribute('aria-pressed',String(button.dataset[selector.includes('meal')?'meal':selector.includes('intensity')?'intensity':'session']===value)))}
function setWeight(value,touched=false){const number=value===null||value===undefined||value===''?NaN:Number(value);if(!Number.isFinite(number)){weightValue.textContent='—';weightRange.disabled=true;form.elements.weight.value='';return}const rounded=Math.round(number*10)/10;weightRange.disabled=false;weightRange.min=String(Math.max(20,Math.floor((rounded-5)*10)/10));weightRange.max=String(Math.min(400,Math.ceil((rounded+5)*10)/10));weightRange.value=String(rounded);form.elements.weight.value=String(rounded);weightValue.textContent=rounded.toFixed(1)+' kg';if(touched)form.dataset.weightTouched='true'}
function setPain(values,intensity=null){const selected=new Set(values);document.querySelectorAll('[data-pain]').forEach(button=>button.setAttribute('aria-pressed',String(selected.has(button.dataset.pain))));form.elements.pain_areas.value=[...selected].join(',');const hasPain=[...selected].some(value=>value!=='none');document.getElementById('pain-intensity').hidden=!hasPain;if(!hasPain)intensity=null;form.elements.pain_intensity.value=intensity??'';selectOne('[data-intensity]',intensity)}
function setSession(status,rpe=null){form.elements.session_status.value=status??'';selectOne('[data-session]',status);const box=document.getElementById('session-rpe');box.hidden=status!=='completed';form.dataset.rpeTouched=String(status==='completed'&&rpe!==null);form.elements.session_rpe.value=rpe??'';if(rpe!==null){document.getElementById('session-rpe-range').value=String(rpe);document.getElementById('session-rpe-value').textContent=String(rpe)}}
function loadDay(){const record=own.find(r=>r.date===form.elements.date.value);for(const k of Object.keys(editableLimits))form.elements[k].value=record?.[k]??'';FoodCombination.load(record?.food_combination??null);const previous=[...own].reverse().find(r=>r.weight!==null)?.weight??profile?.weight_kg??null;setWeight(record?.weight??previous);form.dataset.weightTouched=String(record?.weight!==null&&record?.weight!==undefined);weightSource.textContent=record?.weight!==null&&record?.weight!==undefined?'이 날짜에 저장한 값입니다.':previous!==null?'마지막 기록 또는 프로필 값입니다. 조절하면 오늘 체중으로 저장됩니다.':'기준값이 없습니다. 숫자로 한 번 입력하면 다음부터 버튼과 슬라이더를 쓸 수 있습니다.';const meal=record?.meal_amount??null;form.elements.meal_amount.value=meal??'';selectOne('[data-meal]',meal);setPain(record?.pain_areas??[],record?.pain_intensity??null);setSession(record?.session_status??null,record?.session_rpe??null);document.getElementById('delete-record').hidden=!record}
function openLog(dateValue){form.reset();form.elements.date.value=typeof dateValue==='string'?dateValue:mode==='own'&&own.length?lastDate():today();document.querySelectorAll('#log-form details').forEach(details=>details.open=false);loadDay();document.getElementById('form-message').textContent='';dialog.showModal()}
window.openLogForDate=openLog;document.getElementById('open-log').onclick=()=>openLog();document.getElementById('close-log').onclick=()=>dialog.close();form.elements.date.onchange=loadDay;
document.getElementById('weight-minus').onclick=()=>{if(!weightRange.disabled)setWeight(Number(form.elements.weight.value)-.1,true)};document.getElementById('weight-plus').onclick=()=>{if(!weightRange.disabled)setWeight(Number(form.elements.weight.value)+.1,true)};weightRange.oninput=()=>setWeight(weightRange.value,true);form.elements.weight.oninput=()=>{const value=form.elements.weight.value;if(value!=='')setWeight(value,true)};
document.querySelectorAll('[data-meal]').forEach(button=>button.onclick=()=>{form.elements.meal_amount.value=button.dataset.meal;selectOne('[data-meal]',button.dataset.meal)});
document.querySelectorAll('[data-pain]').forEach(button=>button.onclick=()=>{const value=button.dataset.pain,current=new Set(form.elements.pain_areas.value.split(',').filter(Boolean));if(value==='none')setPain(current.has('none')?[]:['none']);else{current.delete('none');current.has(value)?current.delete(value):current.add(value);setPain([...current],form.elements.pain_intensity.value||null)}});
document.querySelectorAll('[data-intensity]').forEach(button=>button.onclick=()=>{form.elements.pain_intensity.value=button.dataset.intensity;selectOne('[data-intensity]',button.dataset.intensity)});
document.querySelectorAll('[data-session]').forEach(button=>button.onclick=()=>setSession(button.dataset.session));document.getElementById('session-rpe-range').oninput=e=>{form.dataset.rpeTouched='true';form.elements.session_rpe.value=e.target.value;document.getElementById('session-rpe-value').textContent=e.target.value};
form.onsubmit=e=>{e.preventDefault();try{const existing=own.find(r=>r.date===form.elements.date.value),data={date:form.elements.date.value};for(const k of Object.keys(editableLimits))data[k]=k==='weight'&&form.dataset.weightTouched!=='true'&&!existing?.weight?null:form.elements[k].value===''?null:Number(form.elements[k].value);const foodCombination=FoodCombination.get();data.meals=[];data.food_combination=foodCombination;if(foodCombination)Object.assign(data,foodCombination.totals,{nutrition_source:'mfds'});data.meal_amount=form.elements.meal_amount.value||null;data.pain_areas=form.elements.pain_areas.value.split(',').filter(Boolean);data.pain_intensity=form.elements.pain_intensity.value||null;data.session_status=form.elements.session_status.value||null;data.session_rpe=data.session_status==='completed'&&form.dataset.rpeTouched==='true'?Number(form.elements.session_rpe.value):null;if(data.session_status==='completed'&&form.dataset.rpeTouched!=='true')throw Error('수행 후 RPE 슬라이더를 한 번 조절해 주세요.');if(Object.keys(editableLimits).every(k=>data[k]===null)&&!data.food_combination&&data.meal_amount===null&&!data.pain_areas.length&&data.session_status===null)throw Error('한 항목 이상 선택해 주세요.');validateRows([data]);const before=own;own=validateRows(BodyFlowRecord.upsertRecord(own,data.date,data));mode='own';if(!persist()){own=before;throw Error(storageWarning)}offerUndo(existing??null,data.date,existing?'방금 수정한 기록을 되돌릴 수 있어요.':'방금 입력한 기록을 되돌릴 수 있어요.');render();dialog.close()}catch(e){document.getElementById('form-message').textContent=e.message}};
document.getElementById('delete-record').onclick=()=>{const date=form.elements.date.value,existing=own.find(row=>row.date===date);if(!existing||!confirm('이 날짜의 기록을 삭제할까요?'))return;const before=own;own=validateRows(BodyFlowRecord.removeRecord(own,date));if(!persist()){own=before;document.getElementById('form-message').textContent=storageWarning;return}offerUndo(existing,date,'방금 삭제한 기록을 되돌릴 수 있어요.');render();dialog.close()};
document.getElementById('theme').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('bodyflow.theme',document.documentElement.dataset.theme)}catch{}render()};document.getElementById('demo-mode').onclick=()=>{mode='demo';render()};document.getElementById('own-mode').onclick=()=>{mode='own';render()};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));document.querySelectorAll('[data-days]').forEach(b=>b.onclick=()=>{days=+b.dataset.days;render()});document.querySelectorAll('.replay').forEach(b=>b.onclick=()=>renderChart(b.dataset.chart));
function showTip(event){const n=event.target.closest('[data-tip]');if(n){const card=n.closest('.chart-card');card.querySelector('.readout').textContent=n.dataset.tip;}}
document.addEventListener('click',showTip);document.addEventListener('focusin',showTip);document.addEventListener('pointerover',showTip);document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-tip]')){e.preventDefault();showTip(e)}});
document.getElementById('export-data').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,records:own,profile},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='bodyflow-records.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
document.getElementById('import-data').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1000000)throw Error('1MB 이하의 기록 파일을 선택하세요.');const data=JSON.parse(await f.text());if(data.version!==1)throw Error('지원하지 않는 파일 버전입니다.');const incoming=validateRows(await FoodCombination.verifyImportedRows(data.records));const merged=new Map(own.map(r=>[r.date,r]));incoming.forEach(r=>merged.set(r.date,r));const nextRows=validateRows([...merged.values()]);const nextProfile=Object.hasOwn(data,'profile')?validateProfile(data.profile):profile;localStorage.setItem(STORAGE,JSON.stringify({version:1,records:nextRows,profile:nextProfile}));own=nextRows;profile=nextProfile;mode='own';storageWarning='기록과 프로필을 이 기기에 저장했습니다.';render();refreshProfileUI()}catch(e){storageWarning='불러오기 오류: '+e.message;document.getElementById('storage-notice').textContent=storageWarning}finally{e.target.value=''}};
const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){renderChart(entry.target.id);observer.unobserve(entry.target)}},{threshold:.25});document.querySelectorAll('.plot svg').forEach(s=>observer.observe(s));
window.addEventListener('hashchange',()=>{if(location.hash.slice(1)!==tab)setTab(location.hash.slice(1))});render();setTab(location.hash.slice(1));
