'use strict';
const FOOD_RECENT='bodyflow.recent-foods.v1';
const FOOD_FIELDS=['id','name','serving_size_g','kcal','carb_g','protein_g','fat_g','sodium_mg','source','source_id','fetched_at'];
let selectedFoods=[];
const foodById=new Map();
const foodNodes={query:document.getElementById('food-query'),results:document.getElementById('food-results'),recent:document.getElementById('recent-foods'),status:document.getElementById('food-search-status'),items:document.getElementById('combination-items'),totals:document.getElementById('combination-totals'),name:document.getElementById('combination-name')};
function validFood(item){return item&&Object.keys(item).length===FOOD_FIELDS.length&&FOOD_FIELDS.every(key=>Object.hasOwn(item,key))&&item.source==='mfds'&&item.id==='mfds:'+item.source_id&&typeof item.name==='string'&&item.name.length>0&&['serving_size_g','kcal','carb_g','protein_g','fat_g','sodium_mg'].every(key=>typeof item[key]==='number'&&Number.isFinite(item[key])&&item[key]>=0)}
function immutableFood(item){if(!validFood(item))throw Error('식약처 음식 데이터 형식을 확인할 수 없습니다.');return Object.freeze(Object.fromEntries(FOOD_FIELDS.map(key=>[key,item[key]])))}
function badgeValue(label,value,unit){const span=document.createElement('span');span.className='source-value';span.append(document.createTextNode(`${label} ${value}${unit} `));const badge=document.createElement('span');badge.className='mfds-badge';badge.textContent='식약처';span.append(badge);return span}
function remember(id){let ids=[];try{ids=JSON.parse(localStorage.getItem(FOOD_RECENT)||'[]')}catch{}ids=[id,...ids.filter(value=>value!==id)].slice(0,20);localStorage.setItem(FOOD_RECENT,JSON.stringify(ids))}
function card(item,buttonText='조합에 추가'){foodById.set(item.id,item);const article=document.createElement('article');article.className='food-card';const head=document.createElement('div');head.className='food-card-head';const title=document.createElement('h5');title.textContent=item.name;const button=document.createElement('button');button.type='button';button.textContent=buttonText;button.disabled=item.serving_size_g<=0;button.onclick=()=>addFood(item);head.append(title,button);const values=document.createElement('p');values.className='food-values';values.append(badgeValue('기준',item.serving_size_g,'g'),badgeValue('열량',item.kcal,'kcal'),badgeValue('탄수',item.carb_g,'g'),badgeValue('단백',item.protein_g,'g'),badgeValue('지방',item.fat_g,'g'),badgeValue('나트륨',item.sodium_mg,'mg'));article.append(head,values);if(item.serving_size_g<=0){const warning=document.createElement('p');warning.textContent='식약처 기준 제공량이 없어 조합 계산에 사용할 수 없습니다.';article.append(warning)}return article}
function renderCards(host,items,label){host.replaceChildren();if(!items.length){const p=document.createElement('p');p.className='food-empty';p.textContent=label;host.append(p);return}items.forEach(item=>host.append(card(item)))}
async function requestJson(url){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),2900);try{const response=await fetch(url,{signal:controller.signal,headers:{Accept:'application/json'}});const data=await response.json();if(!response.ok)throw Error(data.error||'검색을 완료하지 못했습니다.');return data}finally{clearTimeout(timer)}}
async function loadRecent(){let ids=[];try{ids=JSON.parse(localStorage.getItem(FOOD_RECENT)||'[]').filter(value=>typeof value==='string').slice(0,20)}catch{}if(!ids.length)return renderCards(foodNodes.recent,[],'최근 기록한 음식이 없습니다.');try{const query=ids.map(id=>'id='+encodeURIComponent(id)).join('&');const data=await requestJson('/api/foods/recent?'+query);const items=data.items.map(immutableFood);renderCards(foodNodes.recent,items,'최근 기록한 음식이 없습니다.')}catch{renderCards(foodNodes.recent,[],'서버 캐시에 연결하면 최근 음식이 표시됩니다.') }}
async function searchFoods(){const query=foodNodes.query.value.trim();if(!query){foodNodes.status.textContent='검색어를 입력해 주세요.';return}foodNodes.status.textContent='식약처 DB를 검색하고 있습니다.';foodNodes.results.replaceChildren();try{const started=performance.now(),data=await requestJson('/api/foods?query='+encodeURIComponent(query));const items=(data.items||[]).map(immutableFood),suggestions=(data.suggestions||[]).map(immutableFood);if(items.length){foodNodes.status.textContent=`${items.length}개 결과 · ${data.served_from==='cache'?'로컬 캐시':'식약처 API'} · ${Math.round(performance.now()-started)}ms`;renderCards(foodNodes.results,items,'검색 결과가 없습니다.')}else{foodNodes.status.textContent='이 음식은 아직 데이터가 없어요. 비슷한 것으로 기록할까요?';renderCards(foodNodes.results,suggestions,'제안할 수 있는 식약처 항목도 아직 없습니다.')}}catch(error){foodNodes.status.textContent=error.name==='AbortError'?'검색이 3초 안에 끝나지 않았습니다. 로컬 캐시 연결을 확인해 주세요.':error.message;renderCards(foodNodes.results,[],'식약처 API와 로컬 캐시에 연결하지 못했습니다.')}}
function addFood(food){const existing=selectedFoods.find(entry=>entry.food.id===food.id);if(existing)existing.amount_g=Math.min(5000,existing.amount_g+10);else selectedFoods.push({food,amount_g:food.serving_size_g});remember(food.id);renderCombination();loadRecent()}
function totalsOf(entries){const total={kcal:0,carbs:0,protein:0,fat:0,sodium:0};for(const {food,amount_g} of entries){if(!food.serving_size_g)throw Error(`${food.name}의 식약처 기준 제공량이 없습니다.`);const ratio=amount_g/food.serving_size_g;total.kcal+=food.kcal*ratio;total.carbs+=food.carb_g*ratio;total.protein+=food.protein_g*ratio;total.fat+=food.fat_g*ratio;total.sodium+=food.sodium_mg*ratio}for(const key of Object.keys(total))total[key]=Math.round(total[key]*10)/10;return total}
function renderCombination(){foodNodes.items.replaceChildren();if(!selectedFoods.length){foodNodes.items.innerHTML='<p>검색 결과에서 음식을 추가해 주세요.</p>';foodNodes.totals.hidden=true;return}selectedFoods.forEach((entry,index)=>{const row=document.createElement('div');row.className='combination-row';const title=document.createElement('strong');title.textContent=entry.food.name;const minus=document.createElement('button');minus.type='button';minus.textContent='− 10g';minus.onclick=()=>{entry.amount_g=Math.max(10,entry.amount_g-10);renderCombination()};const amount=document.createElement('output');amount.textContent=entry.amount_g+'g';const plus=document.createElement('button');plus.type='button';plus.textContent='+ 10g';plus.onclick=()=>{entry.amount_g=Math.min(5000,entry.amount_g+10);renderCombination()};const remove=document.createElement('button');remove.type='button';remove.textContent='제거';remove.onclick=()=>{selectedFoods.splice(index,1);renderCombination()};row.append(title,minus,amount,plus,remove);foodNodes.items.append(row)});const totals=totalsOf(selectedFoods);foodNodes.totals.replaceChildren();[['열량',totals.kcal,'kcal'],['탄수화물',totals.carbs,'g'],['단백질',totals.protein,'g'],['지방',totals.fat,'g'],['나트륨',totals.sodium,'mg']].forEach(([label,value,unit])=>{const p=document.createElement('p');p.append(badgeValue(label,value,unit));foodNodes.totals.append(p)});foodNodes.totals.hidden=false}
function combinationForSave(){if(!selectedFoods.length)return null;const name=foodNodes.name.value.trim()||'이름 없는 조합';return {name,items:selectedFoods.map(({food,amount_g})=>({food,amount_g})),totals:totalsOf(selectedFoods)}}
function loadCombination(value){selectedFoods=[];foodNodes.name.value=value?.name||'';if(value?.items)for(const entry of value.items){const food=immutableFood(entry.food);if(!Number.isFinite(entry.amount_g)||entry.amount_g<10||entry.amount_g>5000)throw Error('음식 조합 중량을 확인해 주세요.');selectedFoods.push({food,amount_g:entry.amount_g})}renderCombination()}
async function verifyImportedRows(rows){const ids=[...new Set(rows.flatMap(row=>(row.food_combination?.items||[]).map(entry=>entry.food?.id)).filter(Boolean))];if(ids.length>20)throw Error('한 번에 확인할 식약처 음식은 20개 이하여야 합니다.');if(!ids.length){if(rows.some(row=>['kcal','carbs','protein','fat','sodium'].some(key=>row[key]!=null)))throw Error('출처가 확인되지 않는 영양값은 가져올 수 없습니다.');return rows}const query=ids.map(id=>'id='+encodeURIComponent(id)).join('&');const data=await requestJson('/api/foods/recent?'+query);const official=new Map((data.items||[]).map(immutableFood).map(food=>[food.id,food]));if(official.size!==ids.length)throw Error('로컬 식약처 캐시에서 모든 음식 코드를 확인할 수 없습니다.');return rows.map(row=>{if(!row.food_combination)return row;return {...row,food_combination:{...row.food_combination,items:row.food_combination.items.map(entry=>({...entry,food:official.get(entry.food.id)}))}}})}
document.getElementById('food-search-button').onclick=searchFoods;foodNodes.query.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();searchFoods()}};
window.FoodCombination={load:loadCombination,get:combinationForSave,totalsOf,validFood,loadRecent,verifyImportedRows,reset:()=>loadCombination(null)};
loadRecent();renderCombination();
