'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BodyFlowRecord=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const clone=value=>value===undefined?undefined:JSON.parse(JSON.stringify(value));
  const datePattern=/^\d{4}-\d{2}-\d{2}$/;
  function assertDate(date){if(typeof date!=='string'||!datePattern.test(date)||Number.isNaN(Date.parse(date+'T12:00:00Z'))||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)throw Error('기록 날짜를 확인해 주세요.');}
  function previousDate(date){assertDate(date);const value=new Date(date+'T12:00:00Z');value.setUTCDate(value.getUTCDate()-1);return value.toISOString().slice(0,10);}
  function upsertRecord(records,date,patch){assertDate(date);if(!Array.isArray(records)||!patch||typeof patch!=='object'||Array.isArray(patch))throw Error('기록 형식을 확인해 주세요.');const current=records.find(row=>row.date===date)||{date};return [...records.filter(row=>row.date!==date),{...clone(current),...clone(patch),date}].sort((a,b)=>a.date.localeCompare(b.date));}
  function removeRecord(records,date){assertDate(date);return records.filter(row=>row.date!==date).map(clone);}
  function restoreRecord(records,date,record){const without=removeRecord(records,date);return record?upsertRecord(without,date,record):without;}
  function mealPatch(records,date,slot,patch){if(!['breakfast','lunch','dinner'].includes(slot))throw Error('끼니를 확인해 주세요.');const current=records.find(row=>row.date===date);const meals=clone(current?.meals||[]),previous=meals.find(meal=>meal.slot===slot)||{slot,amount:null,food_combination:null};const next={...previous,...clone(patch),slot};return {meals:[...meals.filter(meal=>meal.slot!==slot),next],meal_amount:next.amount,food_combination:next.food_combination};}
  function recordMealAmount(records,date,amount,slot='lunch'){if(!['high','normal','low'].includes(amount))throw Error('식사량을 선택해 주세요.');return upsertRecord(records,date,mealPatch(records,date,slot,{amount}));}
  function recordFoodCombination(records,date,combination,slot='lunch'){if(!combination||!Array.isArray(combination.items)||!combination.items.length)throw Error('저장할 음식 조합을 확인해 주세요.');return upsertRecord(records,date,mealPatch(records,date,slot,{food_combination:combination}));}
  function recordWeight(records,date,weight){if(!Number.isFinite(weight)||weight<20||weight>400)throw Error('체중을 확인해 주세요.');return upsertRecord(records,date,{weight:Math.round(weight*10)/10});}
  function recordSessionStatus(records,date,status,rpe=null){if(!['completed','stopped','skipped'].includes(status))throw Error('세션 결과를 선택해 주세요.');if(status==='completed'&&(!Number.isInteger(rpe)||rpe<1||rpe>10))throw Error('완료 후 RPE를 선택해 주세요.');return upsertRecord(records,date,{session_status:status,session_rpe:status==='completed'?rpe:null});}
  function recordPain(records,date,areas,intensity=null){if(!Array.isArray(areas)||!areas.length||areas.some(area=>!['knee','back','ankle','shoulder','none'].includes(area))||(areas.includes('none')&&areas.length!==1))throw Error('통증 부위를 선택해 주세요.');const hasPain=areas.some(area=>area!=='none');if(hasPain&&!['slight','moderate','severe'].includes(intensity))throw Error('통증 강도를 선택해 주세요.');return upsertRecord(records,date,{pain_areas:[...areas],pain_intensity:hasPain?intensity:null});}
  function copyYesterdayMeal(records,date,slot='lunch'){const previous=records.find(row=>row.date===previousDate(date));if(!previous)return null;const meal=previous.meals?.find(value=>value.slot===slot);if(meal)return upsertRecord(records,date,mealPatch(records,date,slot,{amount:meal.amount,food_combination:meal.food_combination}));if(previous.meals?.length||(!previous.meal_amount&&!previous.food_combination))return null;return upsertRecord(records,date,mealPatch(records,date,slot,{amount:previous.meal_amount??null,food_combination:previous.food_combination??null}));}
  function lastWeight(records,fallback=null){const value=[...records].sort((a,b)=>b.date.localeCompare(a.date)).find(row=>Number.isFinite(row.weight))?.weight;return Number.isFinite(value)?value:Number.isFinite(fallback)?fallback:null;}
  function frequentCombinations(records,limit=6){const seen=new Set(),result=[];for(const row of [...records].sort((a,b)=>b.date.localeCompare(a.date))){const candidates=row.meals?.length?row.meals.map(meal=>meal.food_combination):[row.food_combination];for(const combo of candidates){if(!combo?.items?.length)continue;const key=combo.items.map(entry=>`${entry.food.id}:${entry.amount_g}`).sort().join('|');if(seen.has(key))continue;seen.add(key);result.push(clone(combo));if(result.length===limit)return result;}}return result;}
  return {upsertRecord,removeRecord,restoreRecord,recordMealAmount,recordFoodCombination,recordWeight,recordSessionStatus,recordPain,copyYesterdayMeal,lastWeight,frequentCombinations};
});
