'use strict';
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BodyFlowVoiceParser=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const digits={영:0,공:0,일:1,이:2,삼:3,사:4,오:5,육:6,칠:7,팔:8,구:9};
  const labels={breakfast:'아침',lunch:'점심',dinner:'저녁',high:'많이',normal:'보통',low:'적게',knee:'무릎',back:'허리',ankle:'발목',shoulder:'어깨',slight:'약간',moderate:'보통',severe:'심함'};
  const clean=value=>String(value??'').trim().replace(/,/g,'.').replace(/[!?~]/g,' ').replace(/\.(?!\d)/g,' ').replace(/\s+/g,' ');
  const compact=value=>clean(value).replace(/\s/g,'');
  function koreanInteger(value){let total=0,current=null;for(const char of value){if(Object.hasOwn(digits,char)){current=digits[char];continue}if(char==='십'){total+=(current??1)*10;current=null;continue}if(char==='백'){total+=(current??1)*100;current=null;continue}return null}return total+(current??0)}
  function koreanNumber(value){const [integer,fraction,...rest]=value.split('점');if(rest.length||!integer)return null;const whole=koreanInteger(integer);if(whole===null)return null;if(fraction===undefined)return whole;if(!fraction||[...fraction].some(char=>!Object.hasOwn(digits,char)))return null;return Number(`${whole}.${[...fraction].map(char=>digits[char]).join('')}`)}
  function weight(text){const value=compact(text),hasContext=/(?:체중|몸무게|킬로그램|키로그램|킬로|키로|kg)/i.test(value),core=value.replace(/^(?:체중|몸무게)(?:은|는|이|가)?/,'').replace(/(?:킬로그램|키로그램|킬로|키로|kg)?(?:입니다|이에요|예요|이야|야)?$/i,'');let number=null;if(/^\d{2,3}(?:[.]\d+)?$/.test(core)&&hasContext)number=Number(core);else if(/^[영공일이삼사오육칠팔구십백]+(?:점[영공일이삼사오육칠팔구]+)?$/.test(core))number=koreanNumber(core);return number!==null&&number>=20&&number<=400?{kind:'weight',weight:number,label:`체중 ${number.toFixed(1)} kg`}:null}
  function meal(text){const value=compact(text),slots=[['breakfast','아침'],['lunch','점심'],['dinner','저녁']].filter(([,word])=>value.includes(word)),amounts=[['high','많이'],['normal','보통'],['low','적게']].filter(([,word])=>value.includes(word));if(slots.length!==1||amounts.length!==1)return null;return {kind:'meal',slot:slots[0][0],amount:amounts[0][0],label:`${labels[slots[0][0]]} · ${labels[amounts[0][0]]}`}}
  function pain(text){const value=compact(text);if(!/(?:아파|아팠|아프|불편)/.test(value))return null;const areas=[['knee','무릎'],['back','허리'],['ankle','발목'],['shoulder','어깨']].filter(([,word])=>value.includes(word));if(areas.length!==1)return null;const levels=[['severe',/(?:심하게|심해|너무|많이|엄청)/],['slight',/(?:약간|조금|좀)/],['moderate',/(?:보통)/]].filter(([,pattern])=>pattern.test(value));if(levels.length!==1)return null;return {kind:'pain',areas:[areas[0][0]],intensity:levels[0][0],label:`${labels[areas[0][0]]} · ${labels[levels[0][0]]}`}}
  function completion(text){const value=compact(text);return ['오늘다했어','오늘다했어요','운동다했어','오늘운동완료','세션완료','운동끝났어'].includes(value)?{kind:'completed',label:'오늘 세션 완료'}:null}
  function parse(text){const value=compact(text),weightResult=weight(text),completionResult=completion(text),mealSignal=/(?:아침|점심|저녁)/.test(value)&&/(?:많이|보통|적게)/.test(value),painSignal=/(?:무릎|허리|발목|어깨)/.test(value)&&/(?:아파|아팠|아프|불편)/.test(value);const signals=[Boolean(weightResult),mealSignal,painSignal,Boolean(completionResult)].filter(Boolean);if(signals.length!==1)return null;if(weightResult)return weightResult;if(mealSignal)return meal(text);if(painSignal)return pain(text);return completionResult}
  return {parse};
});
