const assert=require('assert'),fs=require('fs');
const P=require('../app/prescribe.js');
const profile={goal:'diet',height_cm:165,weight_kg:64,rpe:5,pain_areas:['none'],running_experience:'at_least_6_months'};
const date=(week,offset)=>{const value=new Date('2026-06-01T12:00:00Z');value.setUTCDate(value.getUTCDate()+(week-1)*7+offset);return value.toISOString().slice(0,10)};
function simulate(rule){let current=P.generatePlan(profile)[0];const logs=[],triggered=[],totals=[];for(let week=1;week<=12;week++){
  for(let index=0;index<4;index++)logs.push({date:date(week,index+1),sessionId:`example:${rule}:${week}:${index}`,status:rule===4&&index<2?'skipped':'done',rpe:rule===4&&index<2?null:rule===3?9:rule===5?3:5,pain:rule===1&&index===0?{area:'knee',level:'severe'}:rule===2&&index<3?{area:'knee',level:'moderate'}:null});
  const result=P.adjustNextWeek(current,logs,date(week,6));assert(P.weekMinutes(result.after)<=P.weekMinutes(current)*1.1+.02);assert(P.longestRun(result.after)<=P.longestRun(current)*1.5+1e-9);if(result.after.week%4===0){const ratio=P.weekMinutes(result.after)/P.weekMinutes(current);assert(ratio>=.7-.001&&ratio<=.8+.001)}
  if(result.rule){triggered.push(result.rule);assert(result.reason.trim());assert.equal((result.reason.match(/[.!?]/g)||[]).length,1,'reason is one sentence');assert(result.change.reason.trim());assert.deepEqual(Object.keys(result.change).sort(),['after','before','date','reason']);}
  if(result.rule===1){assert(result.after.sessions.filter(session=>session.type==='run').every(session=>session.blocks.every(block=>block.activity!=='run')));assert(result.after.sessions.filter(session=>session.type==='strength').every(session=>session.blocks.every(block=>!(P.movementAreas[block.activity]||[]).includes('knee'))));}
  if(result.rule===2){assert(Math.abs(P.weekMinutes(result.after)/P.weekMinutes(current)-.8)<.001);for(const session of result.after.sessions.filter(session=>session.type==='run')){const total=session.blocks.reduce((sum,block)=>sum+block.minutes,0),run=session.blocks.filter(block=>block.activity==='run').reduce((sum,block)=>sum+block.minutes,0);assert(run<=total*.25+.001)}}
  if(result.rule===3)assert(P.weekMinutes(result.after)<=P.weekMinutes(current)+.001);
  if(result.rule===4&&!result.after.isRecoveryWeek)assert.equal(P.weekMinutes(result.after),P.weekMinutes(current));
  totals.push(P.weekMinutes(result.after));current=result.after;
 }assert(triggered.includes(rule),`rule ${rule} triggered within 12 weeks`);return {rule,weeks:12,trigger_count:triggered.filter(value=>value===rule).length,passed:true};}
const results=[1,2,3,4,5].map(simulate);
const current=P.generatePlan(profile)[1],lowLogs=[];for(let week=1;week<=2;week++)for(let index=0;index<4;index++)lowLogs.push({date:date(week,index+1),sessionId:`example:conflict:${week}:${index}`,status:'done',rpe:3,pain:week===2&&index===0?{area:'shoulder',level:'severe'}:null});const conflict=P.adjustNextWeek(current,lowLogs,date(2,6));assert.equal(conflict.rule,1);assert(conflict.reason.trim());assert(conflict.after.sessions.filter(session=>session.type==='strength').every(session=>session.blocks.every(block=>!(P.movementAreas[block.activity]||[]).includes('shoulder'))));
const highSkipped=lowLogs.map(log=>({...log,status:'skipped',rpe:9,pain:null}));highSkipped[0].status='done';highSkipped[4].status='done';assert.equal(P.adjustNextWeek(current,highSkipped,date(2,6)).rule,3,'high RPE outranks skipped');
const repeatedLogs=lowLogs.map((log,index)=>({...log,rpe:9,pain:index<3?{area:'back',level:'moderate'}:null}));assert.equal(P.adjustNextWeek(current,repeatedLogs,date(2,6)).rule,2,'repeated pain outranks high RPE');
const repeatLogs=lowLogs.map(log=>({...log,status:'skipped',rpe:null,pain:null}));const durations={};let prior=0;for(let week=1;week<=12;week++){const log={date:date(week,1),sessionId:`example:repeat:${week}`,status:'done',rpe:4,pain:null};repeatLogs.push(log);durations[log.sessionId]=20;const cumulative=P.cumulativeMinutes(repeatLogs,durations);assert(cumulative>prior,'repeating exercise adds cumulative minutes');prior=cumulative;}assert.equal(prior,240);
assert.throws(()=>P.adjustNextWeek(current,[{date:'2026-02-30',sessionId:'bad',status:'done',rpe:3,pain:null}]));
const extended=P.extendPlan([current],lowLogs);assert.equal(P.longestRun(extended[0]),0,'extendPlan applies received logs');
fs.writeFileSync('qa/adaptation-results.json',JSON.stringify({passed:true,data:'예시 수행 기록',simulations:results,checks:['severe pain outranks low RPE','repeated pain outranks high RPE','high RPE outranks skipped','all changes have reasons','weekly 10% and continuous-run 1.5x caps','recovery weeks preserved','repeated sessions add cumulative minutes','extendPlan uses logs']},null,2));console.log('Adaptation checks passed: 5 rules × 12 weeks; priority, reasons and cumulative minutes.');
