// 예시 프로필·기록으로 홈 클릭 횟수를 계측한다. 실제 사용자 데이터는 사용하지 않는다.
const {chromium}=require('C:/Users/no32b/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert'),fs=require('fs'),path=require('path');
const profile={goal:'diet',age_band:'30s',sex:'female',height_cm:165,weight_kg:64.2,exercise_sessions_per_week:2,continuous_walk_minutes:30,pain_areas:['none'],running_experience:'none',rpe:4};
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
  const page=await browser.newPage({viewport:{width:390,height:844},acceptDownloads:true}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('file:///'+path.resolve('BodyFlow.html').replaceAll('\\','/'));
  async function reset(){await page.evaluate(profile=>{localStorage.clear();const yesterday=addDays(today(),-1);localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,profile,records:[{date:yesterday,weight:64.2,meals:['breakfast','lunch','dinner'].map(slot=>({slot,amount:'normal',food_combination:null})),meal_amount:'normal'}]}));},profile);await page.reload();await page.evaluate(()=>{window.measuredTaps=0;window.keyboardEvents=0;document.addEventListener('click',()=>window.measuredTaps++,true);document.addEventListener('keydown',()=>window.keyboardEvents++,true)});}
  const results=[];const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.find(row=>row.date===today()));
  async function measure(name,target,action,check){await reset();assert.equal(await page.locator('#meal-check-count').textContent(),'0/3');await action();await check(await saved());const taps=await page.evaluate(()=>window.measuredTaps),keys=await page.evaluate(()=>window.keyboardEvents);assert(taps<=target,`${name}: ${taps} > ${target}`);assert.equal(keys,0,`${name}: 키보드 입력 없음`);results.push({scenario:name,target,taps,keyboard_events:keys,passed:true});}
  await measure('식사 1회 간단 기록',2,async()=>page.locator('[data-quick-meal=normal]').click(),record=>assert.equal(record.meals.length,1));
  await measure('체중 기록',3,async()=>{await page.locator('#quick-weight-open').click();assert.equal(await page.locator('#quick-weight-value').textContent(),'64.2 kg');await page.locator('#quick-weight-plus').click();await page.locator('#quick-weight-save').click();},record=>assert.equal(record.weight,64.3));
  await measure('세션 완료 처리',2,async()=>{await page.locator('[data-quick-session=completed]').click();const slider=page.locator('#quick-rpe-range'),box=await slider.boundingBox();await slider.click({position:{x:box.width*.8,y:box.height/2}});await page.waitForFunction(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.some(row=>row.date===today()&&row.session_status==='completed'));assert(await page.locator('#quick-check-dialog').isVisible());assert(await page.locator('[data-quick-pain=knee]').isEnabled());},record=>{assert.equal(record.session_status,'completed');assert(record.session_rpe>=1&&record.session_rpe<=10)});
  await measure('통증 기록',3,async()=>{await page.locator('#quick-pain-open').click();await page.locator('[data-quick-pain=knee]').click();await page.locator('[data-quick-intensity=moderate]').click();},record=>{assert.deepEqual(record.pain_areas,['knee']);assert.equal(record.pain_intensity,'moderate')});
  await reset();await page.locator('#copy-yesterday-meal').click();assert.equal(await page.evaluate(()=>window.measuredTaps),1);assert.equal((await saved()).meals[0].amount,'normal');
  await page.evaluate(profile=>{const food=index=>({id:'mfds:EXAMPLE-'+index,name:'예시 음식 '+index,serving_size_g:100,kcal:100+index,carb_g:10,protein_g:5,fat_g:2,sodium_mg:20,source:'mfds',source_id:'EXAMPLE-'+index,fetched_at:'2026-09-13T00:00:00+00:00'});const records=Array.from({length:7},(_,index)=>{const combo={name:'예시 조합 '+index,items:[{food:food(index),amount_g:100}],totals:{kcal:100+index,carbs:10,protein:5,fat:2,sodium:20}};return {date:addDays(today(),-index-1),meals:[{slot:'lunch',amount:null,food_combination:combo}],food_combination:combo}});localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,profile,records}))},profile);await page.reload();assert.equal(await page.locator('#frequent-combinations button').count(),6);await page.evaluate(()=>{window.measuredTaps=0;document.addEventListener('click',()=>window.measuredTaps++,true)});await page.locator('#frequent-combinations button').first().click();assert.equal(await page.evaluate(()=>window.measuredTaps),1);assert((await saved()).food_combination);
  await reset();await page.locator('#copy-yesterday-meal').click();const download=page.waitForEvent('download');await page.locator('#export-data').click();const exported=await download;await exported.saveAs('qa/tap-count-export-example.json');const payload=JSON.parse(fs.readFileSync('qa/tap-count-export-example.json','utf8'));assert.equal(payload.version,1);assert(payload.records.at(-1).meals.length>0);await page.evaluate(()=>localStorage.clear());await page.locator('#import-data').setInputFiles('qa/tap-count-export-example.json');await page.waitForFunction(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.length>0);assert.equal(JSON.parse(await page.evaluate(()=>localStorage.getItem('bodyflow.records.v1'))).version,1);
  await reset();await page.screenshot({path:'qa/quick-recording-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);fs.writeFileSync('qa/tap-count-results.json',JSON.stringify({passed:true,data:'예시 프로필·기록',measurement:'홈을 연 뒤 발생한 click 이벤트 수. 슬라이더 조작도 1탭에 포함.',results,extra_checks:['yesterday same meal: 1 tap','frequent combinations: max 6 and 1 tap','JSON v1 export and import includes meal slots','no keyboard input','post-session pain prompt','no page errors']},null,2));
  fs.writeFileSync('qa/tap-count-report.md','| 시나리오 | 목표 | 측정 | 결과 |\n|---|---:|---:|---|\n'+results.map(row=>`| ${row.scenario} | ${row.target}탭 이내 | ${row.taps}탭 | 통과 |`).join('\n')+'\n');console.log(JSON.stringify(results));
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1)});


