const {chromium}=require('C:/Users/no32b/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert'),fs=require('fs'),path=require('path');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///'+path.resolve('BodyFlow.html').replaceAll('\\','/'));await page.waitForFunction(()=>!document.querySelector('#start-session').disabled);
assert.deepEqual(await page.locator('[data-tab]').evaluateAll(ns=>ns.map(n=>n.textContent.replace(/\d+/,'').trim())),['오늘','계획','나의 변화','더보기']);
assert.deepEqual(await page.locator('#today>article').evaluateAll(ns=>ns.map(n=>n.className)),['today-session','today-meals','today-summary']);
assert.equal(await page.locator('#today .primary').count(),1);assert((await page.locator('#start-session').boundingBox()).height>=48);assert(await page.locator('#today-session .sample-badge').isVisible());assert((await page.locator('#today-date-week').textContent()).includes('누적 운동 시간'));assert(!(await page.locator('#today-date-week').textContent()).includes('주차'));assert(!(await page.locator('#plan-week-list').textContent()).includes('주차'));
await page.locator('#start-session').click();assert(await page.locator('#session-dialog').isVisible());assert((await page.locator('#session-dialog-content').textContent()).includes('준비운동'));await page.locator('#close-session').click();
await page.locator('[data-tab=plan]').click();assert.equal(await page.locator('#plan-week-list>.plan-week').count(),4);assert.deepEqual(await page.locator('#plan-week-list>.plan-week').evaluateAll(cards=>cards.map(card=>card.classList.contains('collapsed'))),[false,true,true,true],'only this week expanded');assert((await page.locator('#plan-progress').textContent()).includes('누적 운동 시간'));assert(!(await page.locator('#plan-progress').textContent()).includes('주차'));assert((await page.locator('#plan-history').textContent()).includes('예시:'));
await page.locator('[data-tab=progress]').click();
for(const [group,expected] of [['diet',['nutrition','calories','recipe']],['body',['weight']],['move',['activity','running','pace']]]){await page.locator(`[data-group-tab=${group}]`).click();const shown=await page.locator('#progress .chart-card[data-group]').evaluateAll(cards=>cards.filter(card=>!card.hidden).map(card=>card.querySelector('svg').id.replace('-chart','')));assert.deepEqual(shown,expected,group+' group shows only its charts');if(expected.length>1){assert(await page.locator('#progress .chart-card[data-group]:not([hidden])').evaluateAll(cards=>cards.every(card=>card.classList.contains('collapsed')&&card.querySelector('.chart-summary').offsetHeight>0)),'summaries first');}}
await page.locator('[data-group-tab=move]').click();const firstMove=page.locator('#progress .chart-card[data-group=move]').first();await firstMove.locator('.chart-toggle').click();assert(await firstMove.locator('.plot').isVisible(),'graph expands on tap');assert(await page.evaluate(()=>document.documentElement.scrollHeight)<812*3,'changes tab under three screens');await page.locator('[data-group-tab=diet]').click();
const ids=['nutrition','calories','recipe','weight','activity','running','pace'];for(const id of ids){assert.equal(await page.locator(`#progress #${id}-chart`).count(),1);assert(await page.locator(`#${id}-chart`).evaluate(n=>n.childElementCount>0));}assert.equal(await page.locator('#today svg').count(),0);
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await page.locator('[data-tab=today]').click();await page.screenshot({path:'qa/today-mobile.png',fullPage:true});fs.writeFileSync('qa/information-architecture-results.json',JSON.stringify({passed:true,data:'fixtures/sample-plan.json · 예시 데이터',checks:['three tabs','today content order','one primary action','48px start target','sample badge','session detail','four-week plan','progress and reasons','later weeks collapsed','changes grouped: diet/body/move','summaries first, graph on tap','changes tab under three screens','seven charts in changes','no home charts','mobile width','no page errors']},null,2));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
