const {chromium}=require('C:/Users/no32b/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert'),fs=require('fs'),path=require('path');
const url='file:///'+path.resolve('BodyFlow.html').replaceAll('\\','/');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
  const unsupported=await browser.newContext();await unsupported.addInitScript(()=>{Object.defineProperty(window,'SpeechRecognition',{value:undefined,configurable:true});Object.defineProperty(window,'webkitSpeechRecognition',{value:undefined,configurable:true})});const unsupportedPage=await unsupported.newPage(),unsupportedErrors=[];unsupportedPage.on('pageerror',error=>unsupportedErrors.push(error.message));await unsupportedPage.goto(url);assert(await unsupportedPage.locator('#voice-record-open').isHidden());assert.deepEqual(unsupportedErrors,[]);await unsupported.close();
  const context=await browser.newContext({viewport:{width:390,height:844}});await context.addInitScript(()=>{window.__voiceTranscript='';class Recognition{start(){queueMicrotask(()=>{this.onresult?.({results:[[{transcript:window.__voiceTranscript}]]});this.onend?.()})}stop(){this.onend?.()}}Object.defineProperty(window,'SpeechRecognition',{value:Recognition,configurable:true})});const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(url);await page.evaluate(()=>localStorage.clear());await page.reload();assert(await page.locator('#voice-record-open').isVisible());
  async function hear(text,expected){await page.evaluate(value=>window.__voiceTranscript=value,text);await page.locator('#voice-record-open').click();await page.locator('#voice-interpretation').filter({hasText:expected}).waitFor();}
  await hear('아침만 먹었나','잘 못 알아들었어요. 다시 말씀해주세요');const before=await page.evaluate(()=>localStorage.getItem('bodyflow.records.v1'));assert(await page.locator('#voice-confirm').isHidden());assert.equal(await page.evaluate(()=>localStorage.getItem('bodyflow.records.v1')),before);
  await page.evaluate(()=>window.__voiceTranscript='62.3킬로');await page.locator('#voice-retry').click();await page.locator('#voice-interpretation').filter({hasText:'체중 62.3 kg'}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('bodyflow.records.v1')),before);await page.locator('#voice-confirm').click();let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.find(row=>row.date===today()));assert.equal(saved.weight,62.3);assert(!(await page.evaluate(()=>localStorage.getItem('bodyflow.records.v1'))).includes('62.3킬로'));
  await hear('점심 많이 먹었어','점심 · 많이');await page.locator('#voice-confirm').click();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.find(row=>row.date===today()));assert.equal(saved.meals.find(meal=>meal.slot==='lunch').amount,'high');
  await hear('무릎이 좀 아팠어','무릎 · 약간');await page.locator('#voice-confirm').click();saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.find(row=>row.date===today()));assert.deepEqual(saved.pain_areas,['knee']);assert.equal(saved.pain_intensity,'slight');
  await page.evaluate(()=>localStorage.clear());await page.reload();await hear('오늘 다 했어','오늘 세션 완료');await page.screenshot({path:'qa/voice-recording-mobile.png',fullPage:true});await page.locator('#voice-confirm').click();assert(await page.locator('#quick-check-dialog').isVisible());saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1'))?.records.find(row=>row.date===today()));assert.equal(saved,undefined);const slider=page.locator('#quick-rpe-range'),box=await slider.boundingBox();await slider.click({position:{x:box.width*.7,y:box.height/2}});saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.find(row=>row.date===today()));assert.equal(saved.session_status,'completed');assert(saved.session_rpe>=1&&saved.session_rpe<=10);
  assert.deepEqual(errors,[]);fs.writeFileSync('qa/voice-results.json',JSON.stringify({passed:true,locale:'ko-KR',parser_variants:20,checks:['four supported patterns','confirmation before save','unrecognized transcript stores nothing','unsupported browser hides button','transcript not persisted','completion continues to RPE','no page errors']},null,2));console.log('Voice browser checks passed.');await context.close();
}finally{await browser.close()}})().catch(error=>{console.error(error);process.exit(1)});
