// 요약 및 복귀 흐름 테스트. 날짜와 기록은 테스트용 예시 입력이다.
const {chromium}=require('C:/Users/no32b/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert'),fs=require('fs'),path=require('path');
const url='file:///'+path.resolve('BodyFlow.html').replaceAll('\\','/');
const isoOffset=n=>{const d=new Date();d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const profile={goal:'diet',age_band:'30s',sex:'female',height_cm:165,weight_kg:64,exercise_sessions_per_week:3,continuous_walk_minutes:40,pain_areas:['none'],running_experience:'under_6_months',rpe:5};
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);
 await page.locator('[data-tab=progress]').click();assert.equal(await page.locator('.chart-summary').count(),7);assert(await page.locator('.chart-card').evaluateAll(cards=>cards.every(card=>{const summary=card.querySelector('.chart-summary'),plot=card.querySelector('.plot');return !plot||summary&&summary.compareDocumentPosition(plot)&Node.DOCUMENT_POSITION_FOLLOWING})));assert(await page.locator('.chart-summary').evaluateAll(nodes=>nodes.every(node=>node.textContent.trim().length>0)));
 await page.evaluate(profile=>{localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,records:[],profile}));localStorage.setItem('bodyflow.lastAccess.v1',new Date().toLocaleDateString('sv-SE'));},profile);await page.reload();await page.locator('[data-tab=progress]').click();await page.locator('#own-mode').click();for(const id of ['nutrition','calories','weight','activity'])assert.equal(await page.locator(`#${id}-chart`).locator('xpath=ancestor::article[1]').locator('.chart-summary').textContent(),'아직 비교할 기록이 부족해요');
 // 어제 기록이 비어 있으면 날짜가 미리 선택된 바로가기를 제공한다.
 await page.evaluate(({profile,date})=>{localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,records:[{date,weight:64}],profile}));localStorage.setItem('bodyflow.lastAccess.v1',new Date().toLocaleDateString('sv-SE'));},{profile,date:isoOffset(-2)});await page.reload();await page.waitForFunction(()=>!document.querySelector('#recovery-banner').hidden);assert((await page.locator('#recovery-banner').textContent()).includes('어제 것도 기록할까요?'));await page.locator('[data-tab=today]').click();await page.screenshot({path:'qa/recovery-yesterday-mobile.png',fullPage:true});const yesterdayButton=page.locator('#recovery-banner button');assert.equal(await yesterdayButton.textContent(),'어제 기록하기');await yesterdayButton.click();assert.equal(await page.locator('[name=date]').inputValue(),isoOffset(-1));await page.locator('#close-log').click();
 // 7일 이상 뒤 복귀해도 온보딩으로 돌리지 않고 낮은 주차를 제안한다.
 await page.evaluate(({profile,date})=>{localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,records:[{date,session_status:'completed',session_rpe:4}],profile}));localStorage.setItem('bodyflow.lastAccess.v1',date);},{profile,date:isoOffset(-8)});await page.reload();await page.waitForFunction(()=>document.querySelector('#recovery-banner').textContent.includes('다시 시작해요'));assert((await page.locator('#recovery-banner').textContent()).includes('1주차부터 하시는 걸 권해요'));assert(!(await page.locator('#profile-dialog').isVisible()));await page.evaluate(()=>{const plan=structuredClone(BODYFLOW_SAMPLE_PLAN);plan.current_progress={week:4,completed_sessions:0,total_sessions:3};renderRecovery(plan)});assert((await page.locator('#recovery-banner').textContent()).includes('2주차부터 하시는 걸 권해요'));await page.screenshot({path:'qa/recovery-return-mobile.png',fullPage:true});
 // 삭제 확인과 직전 삭제 되돌리기.
 await page.evaluate(date=>openLogForDate(date),isoOffset(-8));page.once('dialog',dialog=>dialog.accept());await page.locator('#delete-record').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.length),0);await page.locator('#undo-record').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.length),1);
 // 직전 신규 입력도 되돌릴 수 있다.
 await page.evaluate(profile=>localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,records:[],profile})),profile);await page.reload();await page.locator('#open-log').click();await page.locator('[data-meal=normal]').click();await page.locator('.save-record').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.length),1);await page.locator('#undo-record').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.length),0);
 await page.locator('[data-tab=progress]').click();await page.screenshot({path:'qa/chart-summaries-mobile.png',fullPage:true});assert.deepEqual(errors,[]);
 fs.writeFileSync('qa/insights-recovery-results.json',JSON.stringify({passed:true,data:'예시 기록',checks:['seven summaries above charts','insufficient data copy','yesterday shortcut','eight-day return recommendation','no onboarding reset','delete confirmation','undo delete','undo latest input','no page errors']},null,2));
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1)});
