const {chromium}=require('C:/Users/no32b/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert'),fs=require('fs'),path=require('path'),P=require('../app/prescribe.js');
const url='file:///'+path.resolve('BodyFlow.html').replaceAll('\\','/'),profile={goal:'diet',age_band:'30s',sex:'female',height_cm:165,weight_kg:64,exercise_sessions_per_week:3,continuous_walk_minutes:40,pain_areas:['none'],running_experience:'at_least_6_months',rpe:5};
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(url);
  const setRecords=async severity=>page.evaluate(({profile,severity})=>{localStorage.clear();const rows=[-2,-1,0].map((offset,index)=>{const d=new Date();d.setDate(d.getDate()+offset);const hasPain=severity==='moderate'||index===2;return {date:d.toLocaleDateString('sv-SE'),strength:20,session_status:'completed',session_rpe:3,pain_areas:hasPain?['shoulder']:[],pain_intensity:hasPain?severity:null}});localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,profile,records:rows}))},{profile,severity});
  await setRecords('severe');await page.reload();await page.locator('[data-tab=plan]').click();await page.locator('#adaptive-proposal').waitFor();assert((await page.locator('#adaptive-reason').textContent()).includes('심한 통증'));assert.equal(await page.locator('#plan-progress').textContent(),'누적 운동 시간 60분');let state=await page.evaluate(()=>BodyFlowAdaptive.state()),baseline=state.weeks[1];assert(state.sessionLogs.every(log=>JSON.stringify(Object.keys(log).sort())===JSON.stringify(['date','pain','rpe','sessionId','status'])));
  await page.locator('#adaptive-reject').click();assert(await page.locator('#adaptive-warning').isVisible());assert.equal((await page.evaluate(()=>BodyFlowAdaptive.state())).changes.length,0);await page.screenshot({path:'qa/adaptive-warning-mobile.png',fullPage:true});await page.locator('#adaptive-reject').click();assert(await page.locator('#adaptive-proposal').isHidden());state=await page.evaluate(()=>BodyFlowAdaptive.state());assert.equal(state.changes.length,0);assert.deepEqual(state.weeks[1],baseline);
  await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('bodyflow.adaptive-plan.v1'));value.decisions={};localStorage.setItem('bodyflow.adaptive-plan.v1',JSON.stringify(value))});await page.reload();await page.locator('[data-tab=plan]').click();await page.locator('#adaptive-accept').click();state=await page.evaluate(()=>BodyFlowAdaptive.state());assert.equal(state.changes.length,1);assert(state.changes[0].reason.trim());assert(state.changes[0].after.sessions.filter(session=>session.type==='run').every(session=>session.blocks.every(block=>block.activity!=='run')));assert(state.changes[0].after.sessions.filter(session=>session.type==='strength').every(session=>session.blocks.every(block=>!(P.movementAreas[block.activity]||[]).includes('shoulder'))));await page.reload();await page.locator('[data-tab=plan]').click();assert((await page.locator('#plan-history').textContent()).includes(state.changes[0].reason));assert.equal(await page.locator('#plan-progress').textContent(),'누적 운동 시간 60분');await page.screenshot({path:'qa/adaptive-plan-mobile.png',fullPage:true});
  await setRecords('moderate');await page.reload();await page.locator('[data-tab=plan]').click();await page.locator('#adaptive-proposal').waitFor();assert((await page.locator('#adaptive-reason').textContent()).includes('3번'));await page.locator('#adaptive-reject').click();assert(await page.locator('#adaptive-proposal').isHidden());assert(await page.locator('#adaptive-warning').isHidden());
  await page.evaluate(profile=>{localStorage.clear();const rows=[-2,-1,0].map(offset=>{const d=new Date();d.setDate(d.getDate()+offset);return {date:d.toLocaleDateString('sv-SE'),strength:20,session_status:'completed',session_rpe:3,pain_areas:['knee','ankle'],pain_intensity:'moderate'}});localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,profile,records:rows}))},profile);await page.reload();await page.locator('[data-tab=plan]').click();await page.locator('#adaptive-proposal').waitFor();const multiReason=await page.locator('#adaptive-reason').textContent();assert(multiReason.includes('무릎')&&multiReason.includes('발목'),'multi-area reason names both areas');assert.equal(await page.locator('#adaptive-status').textContent(),'','multi-area pain is not put on hold');assert((await page.evaluate(()=>BodyFlowAdaptive.state())).sessionLogs.every(log=>Array.isArray(log.pain)&&log.pain.length===2));
  // 러닝 차트는 내 기록 모드에서 이번 주 계획의 걷기·달리기 세션을 그린다.
  await page.locator('[data-tab=progress]').click();await page.locator('#own-mode').click();const running=await page.evaluate(()=>{const state=BodyFlowAdaptive.state(),index=Math.floor((Date.parse(new Date().toLocaleDateString('sv-SE')+'T12:00:00')-Date.parse(state.startDate+'T12:00:00'))/86400000/7),session=state.weeks[index].sessions.find(item=>item.type==='run'),sum=activity=>Math.round(session.blocks.filter(block=>block.activity===activity).reduce((total,block)=>total+block.minutes,0)),card=document.querySelector('#running-chart').closest('article');return {walk:sum('walk'),run:sum('run'),warm:Math.round(session.warmup_min),summary:card.querySelector('.chart-summary').textContent,sub:card.querySelector('.sub').textContent,src:card.querySelector('.src').textContent,mainRow:[...card.querySelectorAll('tbody tr, tr')].map(tr=>[...tr.children].map(td=>td.textContent)).find(row=>row[0]==='본운동'),rungs:document.querySelectorAll('#running-chart line').length}});
  assert.equal(running.summary,`이번 주 계획 세션은 걷기 ${running.walk}분과 달리기 ${running.run}분으로 구성돼요`);assert(running.sub.includes(`준비 ${running.warm}분`));assert(running.src.includes('내 계획'));assert.deepEqual(running.mainRow,['본운동',String(running.walk),String(running.run),'0']);assert(running.rungs>1,'plan session drawn');
  await page.locator('#demo-mode').click();assert((await page.locator('#running-chart').locator('xpath=ancestor::article[1]').locator('.chart-summary').textContent()).startsWith('예시 세션은'));await page.locator('[data-tab=plan]').click();
  // 쉬는 주간(3곳 이상 통증) 제안은 거절할 때 경고를 한 번 더 띄운다.
  await page.evaluate(profile=>{localStorage.clear();const rows=[-2,-1,0].map(offset=>{const d=new Date();d.setDate(d.getDate()+offset);return {date:d.toLocaleDateString('sv-SE'),strength:20,session_status:'completed',session_rpe:3,pain_areas:offset===0?['knee','ankle','back']:[],pain_intensity:offset===0?'slight':null}});localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,profile,records:rows}))},profile);await page.reload();await page.locator('[data-tab=plan]').click();await page.locator('#adaptive-proposal').waitFor();assert.equal(await page.locator('#adaptive-reason').textContent(),P.fullRestReason);await page.locator('#adaptive-reject').click();assert(await page.locator('#adaptive-warning').isVisible(),'rest rejection warns');assert((await page.locator('#adaptive-warning').textContent()).includes('여러 곳의 통증'));await page.locator('#adaptive-reject').click();assert(await page.locator('#adaptive-proposal').isHidden());
  // 내 계획 설정: 다음 주부터 반영, 변경 이력에 사유, 이번 주는 그대로.
  const beforeSettings=await page.evaluate(()=>BodyFlowAdaptive.state());assert.deepEqual(beforeSettings.settings,{growth:'standard',minWalk:1});assert.equal(await page.locator('[data-plan-walk="1"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('[data-plan-growth]').count(),0,'no growth-speed option');
  await page.locator('[data-plan-walk="2"]').click();const afterSettings=await page.evaluate(()=>BodyFlowAdaptive.state()),index=Math.floor((Date.parse(new Date().toLocaleDateString('sv-SE')+'T12:00:00')-Date.parse(afterSettings.startDate+'T12:00:00'))/86400000/7);
  assert.deepEqual(afterSettings.settings,{growth:'standard',minWalk:2});assert.deepEqual(afterSettings.weeks[index],beforeSettings.weeks[index],'current week unchanged');assert(afterSettings.weeks.slice(index+1).every(week=>week.sessions.every(session=>session.blocks.every((block,i)=>!(block.activity==='walk'&&session.blocks[i-1]?.activity==='run')||block.minutes>=2-1e-9))),'future walk intervals at least 2 minutes');assert((await page.locator('#plan-history').textContent()).includes('계획 설정을'));assert.equal(await page.locator('[data-plan-walk="2"]').getAttribute('aria-pressed'),'true');
  await page.reload();await page.locator('[data-tab=plan]').click();assert.equal(await page.locator('[data-plan-walk="2"]').getAttribute('aria-pressed'),'true','settings persist');
  // 예전에 저장된 '천천히' 설정은 기본으로 옮기고 다음 주부터 다시 계산한다.
  await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('bodyflow.adaptive-plan.v1'));value.settings={growth:'gentle',minWalk:1};localStorage.setItem('bodyflow.adaptive-plan.v1',JSON.stringify(value))});await page.reload();await page.locator('[data-tab=plan]').click();const migrated=await page.evaluate(()=>BodyFlowAdaptive.state());assert.deepEqual(migrated.settings,{growth:'standard',minWalk:1});assert(migrated.changes.at(-1).reason.includes('천천히 늘리기 설정이 없어져'));assert.equal(await page.locator('#adaptive-status').textContent(),'','legacy setting does not break loading');
  const visible=await page.locator('#plan').textContent();for(const phrase of ['되돌아'+'감','실'+'패','단계 '+'하락'])assert(!visible.includes(phrase));assert.deepEqual(errors,[]);fs.writeFileSync('qa/adaptive-plan-browser-results.json',JSON.stringify({passed:true,data:'예시 수행 기록',checks:['cumulative minutes instead of week progress','severe pain proposal','severe rejection warns once more','second rejection keeps baseline unchanged','accepted change persists with reason','running becomes walking','strength avoids pain area','non-severe rejection needs one confirmation','multi-area pain adjusts both areas','running chart follows own plan session','rest-week rejection warns once more','plan settings apply from next week and persist','no discouraged wording','no page errors']},null,2));console.log('Adaptive plan browser checks passed.');
}finally{await browser.close()}})().catch(error=>{console.error(error);process.exit(1)});
