// 식약처 형식의 예시 응답만 쓰는 음식 검색·조합 브라우저 검증.
const {chromium}=require('C:/Users/no32b/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {spawn}=require('child_process'),assert=require('assert'),fs=require('fs'),path=require('path');
const python='C:/Users/no32b/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',port=18769;
function ready(proc){return new Promise((resolve,reject)=>{let text='';proc.stdout.on('data',chunk=>{text+=chunk;if(text.includes('READY'))resolve()});proc.stderr.on('data',chunk=>{text+=chunk});proc.on('exit',code=>reject(Error(`server exited ${code}: ${text}`)));setTimeout(()=>reject(Error('server start timeout')),5000)})}
(async()=>{const server=spawn(python,['food_test_server.py','--port',String(port)],{cwd:__dirname});let browser;try{await ready(server);browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(`http://127.0.0.1:${port}/`);await page.locator('#open-log').click();await page.locator('#food-combination summary').click();await page.locator('#food-query').fill('ㄱㅁㅅ');const started=Date.now();await page.locator('#food-search-button').click();await page.waitForFunction(()=>document.querySelectorAll('#food-results .food-card').length>0);assert(Date.now()-started<3000);assert((await page.locator('#food-search-status').textContent()).includes('로컬 캐시'));await page.locator('#food-results .food-card button').first().click();assert.equal(await page.locator('#combination-totals .mfds-badge').count(),5);assert((await page.locator('#recent-foods').textContent()).includes('고구마'));await page.locator('#combination-name').fill('예시 내 점심');await page.evaluate(()=>document.querySelector('#log-form').requestSubmit());await page.waitForTimeout(100);const record=await page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records[0]);assert.equal(record.nutrition_source,'mfds');assert.equal(record.food_combination.name,'예시 내 점심');assert(record.kcal>0);assert.equal(await page.locator('input[name=kcal],input[name=carbs],input[name=protein],input[name=fat],input[name=sodium]').count(),0);await page.locator('#open-log').click();await page.locator('#food-combination summary').click();await page.locator('#food-query').fill('없는음식xyz');await page.locator('#food-search-button').click();await page.waitForFunction(()=>document.querySelector('#food-search-status').textContent.includes('이 음식은 아직 데이터가 없어요'));assert.equal(await page.locator('#food-results .food-card').count(),3);assert.deepEqual(errors,[]);fs.writeFileSync(path.resolve(__dirname,'../qa/food-browser-results.json'),JSON.stringify({passed:true,data:'식약처 형식 예시 응답',checks:['initial consonant search','under 3 seconds','API failure cache fallback','recent foods at top','combination calculation','MFDS badges','no nutrient inputs','missing item message','three similar suggestions','no page errors']},null,2));console.log('Food browser checks passed.')}finally{if(browser)await browser.close();server.kill();}})().catch(error=>{console.error(error);process.exit(1)});









