// 요약 및 복귀 흐름 테스트. 날짜와 기록은 테스트용 예시 입력이다.
const {chromium}=require('C:/Users/no32b/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert'),fs=require('fs'),path=require('path');
const url='file:///'+path.resolve('BodyFlow.html').replaceAll('\\','/');
const isoOffset=n=>{const d=new Date();d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const profile={goal:'diet',age_band:'30s',sex:'female',height_cm:165,weight_kg:64,exercise_sessions_per_week:3,continuous_walk_minutes:40,pain_areas:['none'],running_experience:'under_6_months',rpe:5};
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);
 await page.locator('[data-tab=progress]').click();assert.equal(await page.locator('.chart-summary').count(),7);assert(await page.locator('.chart-card').evaluateAll(cards=>cards.every(card=>{const summary=card.querySelector('.chart-summary'),plot=card.querySelector('.plot');return !plot||summary&&summary.compareDocumentPosition(plot)&Node.DOCUMENT_POSITION_FOLLOWING})));assert(await page.locator('.chart-summary').evaluateAll(nodes=>nodes.every(node=>node.textContent.trim().length>0)));
 // 예시 러닝·페이스 요약은 차트 데이터 표와 같은 값을 쓴다.
 const exampleSummaries=await page.evaluate(()=>{const running=tableFor('running-chart').slice(1),pace=tableFor('pace-chart').slice(1).filter(row=>/^\d+ km$/.test(row[0])).at(-1);return {walk:running.reduce((sum,row)=>sum+row[1],0),run:running.reduce((sum,row)=>sum+row[2],0),pace,runningText:document.querySelector('#running-chart').closest('article').querySelector('.chart-summary').textContent,paceText:document.querySelector('#pace-chart').closest('article').querySelector('.chart-summary').textContent}});assert.equal(exampleSummaries.runningText,`예시 세션은 걷기 ${exampleSummaries.walk}분과 달리기 ${exampleSummaries.run}분으로 구성돼요`);assert.equal(exampleSummaries.paceText,`예시 ${exampleSummaries.pace[0]} 구간 기록은 ${exampleSummaries.pace[1]}예요`);
 await page.evaluate(profile=>{localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,records:[],profile}));localStorage.setItem('bodyflow.lastAccess.v1',new Date().toLocaleDateString('sv-SE'));},profile);await page.reload();await page.locator('[data-tab=progress]').click();await page.locator('#own-mode').click();for(const id of ['nutrition','calories','weight','activity'])assert.equal(await page.locator(`#${id}-chart`).locator('xpath=ancestor::article[1]').locator('.chart-summary').textContent(),'아직 비교할 기록이 부족해요');
 // 어제 기록이 비어 있으면 날짜가 미리 선택된 바로가기를 제공한다.
 await page.evaluate(({profile,date})=>{localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,records:[{date,weight:64}],profile}));localStorage.setItem('bodyflow.lastAccess.v1',new Date().toLocaleDateString('sv-SE'));},{profile,date:isoOffset(-2)});await page.reload();await page.waitForFunction(()=>!document.querySelector('#recovery-banner').hidden);assert((await page.locator('#recovery-banner').textContent()).includes('어제 것도 기록할까요?'));await page.locator('[data-tab=today]').click();await page.screenshot({path:'qa/recovery-yesterday-mobile.png',fullPage:true});const yesterdayButton=page.locator('#recovery-banner button');assert.equal(await yesterdayButton.textContent(),'어제 기록하기');await yesterdayButton.click();assert.equal(await page.locator('[name=date]').inputValue(),isoOffset(-1));await page.locator('#close-log').click();
 // 7일 이상 뒤 복귀해도 온보딩으로 돌리지 않고 낮은 주차를 제안한다.
 await page.evaluate(({profile,date})=>{localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,records:[{date,session_status:'completed',session_rpe:4}],profile}));localStorage.setItem('bodyflow.lastAccess.v1',date);},{profile,date:isoOffset(-8)});await page.reload();await page.waitForFunction(()=>document.querySelector('#recovery-banner').textContent.includes('다시 시작해요'));assert((await page.locator('#recovery-banner').textContent()).includes('1주차부터 하시는 걸 권해요'));assert(!(await page.locator('#profile-dialog').isVisible()));assert((await page.locator('#recovery-banner').textContent()).includes('내 계획'));
 // 프로필이 없는 예시 모드는 예시 계획 진행도로 완료 주차를 계산한다.
 assert.equal(await page.evaluate(()=>{const plan=structuredClone(BODYFLOW_SAMPLE_PLAN);plan.current_progress={week:4,completed_sessions:0,total_sessions:3};return completedPlanWeek(plan)}),3);
 // 내 계획에서 3주를 모두 완료한 뒤 8일 만에 돌아오면 한 주 낮춘 2주차를 권한다. 예시 계획 진행도는 섞지 않는다.
 await page.evaluate(()=>{const offset={monday:0,tuesday:1,wednesday:2,thursday:3,friday:4,saturday:5,sunday:6},iso=d=>d.toLocaleDateString('sv-SE'),start=new Date();start.setDate(start.getDate()-35);start.setDate(start.getDate()-((start.getDay()+6)%7));const startDate=iso(start),weeks=BodyFlowPrescription.generatePlan(profile),records=[];for(let index=0;index<3;index++)for(const session of weeks[index].sessions){const d=new Date(start);d.setDate(d.getDate()+index*7+offset[session.day]);records.push({date:iso(d),session_status:'completed',session_rpe:4})}const last=new Date();last.setDate(last.getDate()-8);localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,records,profile}));localStorage.setItem('bodyflow.adaptive-plan.v1',JSON.stringify({version:1,profileSignature:JSON.stringify(profile),startDate,weeks,sessionLogs:[],changes:[],decisions:{},durations:{}}));localStorage.setItem('bodyflow.lastAccess.v1',iso(last))});await page.reload();await page.waitForFunction(()=>document.querySelector('#recovery-banner').textContent.includes('다시 시작해요'));const ownReturn=await page.locator('#recovery-banner').textContent();assert(ownReturn.includes('2주차부터 하시는 걸 권해요'),ownReturn);assert(ownReturn.includes('내 계획'));await page.screenshot({path:'qa/recovery-return-mobile.png',fullPage:true});
 // 삭제 확인과 직전 삭제 되돌리기.
 const savedCount=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.length),beforeDelete=await savedCount();await page.evaluate(()=>openLogForDate(own[0].date));page.once('dialog',dialog=>dialog.accept());await page.locator('#delete-record').click();assert.equal(await savedCount(),beforeDelete-1);await page.locator('#undo-record').click();assert.equal(await savedCount(),beforeDelete);
 // 직전 신규 입력도 되돌릴 수 있다.
 await page.evaluate(profile=>localStorage.setItem('bodyflow.records.v1',JSON.stringify({version:1,records:[],profile})),profile);await page.reload();await page.locator('#open-log').click();await page.locator('[data-meal=normal]').click();await page.locator('.save-record').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.length),1);await page.locator('#undo-record').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('bodyflow.records.v1')).records.length),0);
 await page.locator('[data-tab=progress]').click();await page.screenshot({path:'qa/chart-summaries-mobile.png',fullPage:true});assert.deepEqual(errors,[]);
 fs.writeFileSync('qa/insights-recovery-results.json',JSON.stringify({passed:true,data:'예시 기록',checks:['seven summaries above charts','example summaries match chart tables','insufficient data copy','yesterday shortcut','eight-day return recommendation','own plan: last completed week minus one','no onboarding reset','delete confirmation','undo delete','undo latest input','no page errors']},null,2));
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1)});
